---
- name: Ensure local fact directory exists
  become: true
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Register SSH facts locally
  become: true
  ansible.builtin.template:
    src: ssh.facts.j2
    dest: /etc/ansible/facts.d/ssh.fact
    owner: root
    group: root
    mode: "0644"
    force: true
  register: ssh_facts

- name: Reload facts
  ansible.builtin.setup:
    filter: ansible_local
  when: ssh_facts is changed
